### ISSUE TITLE
[Bug] {{file_path:absolute}} / {{folder_path:absolute}} on MacOS >>> missing leading `/`

### ISSUE THREAD

**Issue by FelipeRearden** [Taitava/obsidian-shellcommands#44]
Hello @Taitava !!!

For a best fit with MacOS, is a good idea to include `/` in the beginning of the follow variables:
- {{file_path:absolute}}
- {{folder_path:absolute}}

{{file_path:absolute}} = Users/login/vault/folder/MyNote.md;
MacOS file_path:absolute = /Users/login/vault/folder/MyNote.md

{{folder_path:absolute}} = Users/login/vault/folder;
MacOS folder_path:absolute = /Users/login/vault/folder

Everything is OK with {{vault_path}}

{{vault_path}} = /Users/login/vault/
MacOS vault path = /Users/login/vault/

Have a great day!

**Comment by Taitava** [comment]
> Everything is OK with {{vault_path}}

Thanks for this detail, it's very helpful to know! The same vault path is used as a component for `{{file_path:absolute}}` and `{{folder_path:absolute}}` too, so now I know that the culprit is not where we get the vault path from.

Probably the bug comes from normalizing a join of the vault path and a file/folder relative path. Normalization a is process that should make sure that a path looks sensible. E.g. If you combine Windows paths *C:\Users\username\* and *\SomeFolder\SomeFile.md* (the latter is a relative path), you will get *C:\Users\username\\\\SomeFolder\SomeFile.md*, which has a double backslash *\\\\*. Normalization cleans it up: *C:\Users\username\SomeFolder\SomeFile.md*. But it looks like the normalization likes to eat a leading slash from an absolute path, which makes it incorrectly to a relative path.

I have other stuff that will be released in `0.4.0` (probably today), but I'll try to have this fixed in `0.4.1` which will contain other bug fixes, too.

**Comment by Taitava** [comment]
I just teted `{{file_path:absolute}}` on Linux and yeah, the same happens on Linux too, which was expected.

**Comment by Taitava** [comment]
I've escalated this to Obsidian Forum: https://forum.obsidian.md/t/normalizepath-removes-a-leading/24713

I'm not sure if this is something that Obsidian's devs will consider to be fixed on their side or not (= do they see this as a bug or as a designed feature that works like it should). Whichever is the case, I can make a fix myself in this plugin's code, and time will tell if the fix will be just temporary.

While writing the topic to Obsidian's forum, I also noticed another bug related to this, that affects Windows: all `\` characters in paths are replaced with `/` (exception: `{{vault_path}}` does not have this issue, because it does not use normalization). This is actually a separate bug, but I think I will use this same issue for that one too, and not open a new issue for this.

And while removing leading `/`s first seemed only to affect Mac and Linux, it affects Windows too, because network paths are not left alone by this bug: *\\\\network\\path* becomes *network\\path*.

**Comment by Taitava** [comment]
Todo: Create a wrapper function named `normalizePath2()` that first calls `normalizePath()` and then:
- [ ] Re-adds leading `/`/`\` chracters that were removed by `normalizePath()`. **This must test first that `normalizePath()` did remove the slashes**, so that they won't be repeated in case Obsidian fixes this problem on their side.
- [ ] Converts `/` slashes to `\` slashes, if platform is Windows.

**Comment by Taitava** [comment]
Should be fixed now. Will be released in `0.4.1`.

**Comment by FelipeRearden** [comment]
Thank you very much @Taitava for this fix. Tomorrow I will start my test on`0.4.1` and update our MacOS log :)

**Comment by Taitava** [comment]
You are welcome! 😎

**Comment by FelipeRearden** [comment]
Working perfect on:
Version 0.4.1
MacOS 11.1
Obsidian 0.12.15

**Comment by Taitava** [comment]
Thanks for testing! 😎
