### ISSUE TITLE
Thank you + Question +  [Feature Request] Alias (names) for commands 

### ISSUE THREAD

**Issue by FelipeRearden** [Taitava/obsidian-shellcommands#6]
Hello @Taitava !

## Thank you!

First of all, I want to thank you for this spectacular plug-in. I have been using this plug-in since yesterday and finally I can do things in Obsidian that I was struggling. Because of this plug-in, my workflow in Obsidian is getting smatter :)

## Question

Since I’m not familiar with code, I’m trying to learn how to use the plug-in to improve my workflow. 
- And I wanna know if I can ask for your help if I face some situation  that I can’ find on the internet. 

##Feature Request

My first FR is very simple: the ability to define a name (alias) for every `Command #` that I have  
![e1](https://user-images.githubusercontent.com/85180696/132046633-aa9689ac-b248-47fa-9fe9-6e07e107b67e.png)

I’m facing some difficult to identify my commands on `command palette` :(
![e2](https://user-images.githubusercontent.com/85180696/132046651-f9965678-a938-4369-99c7-ee5b95e4562b.png)

—-
Thank you very much and have a great day!

**Comment by Taitava** [comment]
Thank you for your feedback and feature request! :) Really nice to hear that this plugin has been helpful to you! :)

The idea about aliases is really good. It didn't come to my mind earlier because I have only used a couple of commands myself, and I only launch those commands using hotkeys. Looking at the screenshots of your settings and command palette, it became very clear to me that an alias feature is needed. It will make the command palette much easier to read.

Just to clarify thigs, I'll write a todo list for myself:
 - [ ] Command palette: If a command has an alias, display *Shell commands: Execute: \*COMMAND ALIAS HERE\** instead of the actual command. If the command does not have an alias, display the actual command just like it's currently displayed. (One downside: when the actual command is not displayed in the command palette, you cannot search for that command using keywords like *echo*, *open* or whatever you have in the actual command. But maybe this is not a big issue.)
 - [ ] Settings: Add a *Define alias" button/link next to each command. Clicking it will open a modal/popup that asks for an alias (I think this will save screen space in the settings view). If an alias is defined, *Command #n* should be replaced with the alias text, so the alias is always visible in settings.

**Comment by Taitava** [comment]
And it's a really nice idea to use Obsidian URIs in the commands! I haven't made myself familiar with Obsidian URIs yet so I never though that those can be used in commands too 🙂 . That's one thing I could learn more about.

**Comment by FelipeRearden** [comment]
Hello @Taitava !

Thank you very much for your reply. I’m extremely happy that you like my feature request. :)

**Comment by FelipeRearden** [comment]
> And it's a really nice idea to use Obsidian URIs in the commands! I haven't made myself familiar with Obsidian URIs yet so I never though that those can be used in commands too 🙂 . That's one thing I could learn more about.

That was my first ideia after reading your README ! ShellCommands + Obsidian URI is an amazing combination :)
- My first command is to apply hotkeys for workspaces with Obsidian URI 

I’m glad that I help you with something. When I find more workflows, I will share than with you :)

Have a great day !

**Comment by Taitava** [comment]
Thanks! :)

I'd like to add two Obsidian URI examples to the README (Windows commands):
- A simple example to open another vault: `start "" "obsidian://open?vault=my%20vault"`
- [Advanced URI](https://github.com/Vinzent03/obsidian-advanced-uri) example to open a workspace: `start "" "obsidian://advanced-uri?vault=my%20vault&workspace=main"`

If it's ok to you, I could put your GitHub username & profile link next to those examples? Like:
> Ideas by [FelipeRearden](https://github.com/FelipeRearden) .

And yes, it would be nice if you can share workflow ideas in the future too. :)

**Comment by Taitava** [comment]
Btw I just noticed that I didn't answer this question:
> And I wanna know if I can ask for your help if I face some situation that I can’ find on the internet.

Sure, all help questions can be asked just by creating a new issue. 🙂

**Comment by FelipeRearden** [comment]
Hello @Taitava !

> If it's ok to you, I could put your GitHub username & profile link next to those examples? Like:

Sure! Would be an honor to help our community friends :)

I will bring more ideias in the next weeks :)

**Comment by FelipeRearden** [comment]
> Sure, all help questions can be asked just by creating a new issue. 🙂 Another place to ask for help is [a topic for this plugin in Obsidian's forum](https://forum.obsidian.md/t/shell-commands-plugin/23497).

Thanks for this @Taitava !!!!!

I wish you a fantastic week :)

**Comment by Taitava** [comment]
Thanks @FelipeRearden! I've added the examples to README.md.

And I've created the alias feature. Still a couple of things:
 - I need to test the alias feature more before releasing it.
 - \+ I need to test other code changes that I did in #8 before I was able to implement this feature.
 - When I progress testing things, I'll make two new releases: First `0.1.1` will contain just #8 stuff, and finally `0.2.0` will contain this alias feature. 👍

**Comment by Taitava** [comment]
This is now released 🙂 . The alias setting can be found by clicking a small cog icon next to each command field. Then icon opens up a modal where the alias can be set. In the future, themodal might contain other settings too.

I made it to be an icon to save screen space when there is no big text button. And one reason is also that I'm not yet very experienced in placing new elements to Obsidian's UI, and this seemed to be an easy way for it.

Thanks again @FelipeRearden for this idea and even though I'll close this issue now, you are free to give feedback on this feature by adding comments to this issue! 🙂

**Comment by FelipeRearden** [comment]
Hello @Taitava !!!! 

Sorry for the late reply. This is amazing !!!!!!! 

The new interface is fantastic! I loved the cog icon to define the alias. 
- it's a clever strategy to create space to new features 👀  !

Here is what I'm gonna do .... 
- I will test the new release to see if I find something in the interface and the new commands.
- I will test my previous Shell Commands to see if everything is Okay - **I found something strange in one of my Shell Commands in `0.1.1` compared to `0.0.1` . I will see this now in 0.0.2**
- Since I'm on MacOS I will make the OS test and report to you too (if its okay for you :) )

We talk soon ! Have great day and thanks again for this amazing new release !

**Comment by Taitava** [comment]
Thanks, you replied pretty quickly. 😄 

> I will test my previous Shell Commands to see if everything is Okay - I found something strange in one of my Shell Commands in 0.1.1 compared to 0.0.1 . I will see this now in 0.2.0

Update from `0.1.0` to `0.1.1` migrated shell commands to a new internal saving format. Can it be that something happened to your commands during that migration? I tried to test the migration many times and in my tests it seemed to go smootly, but there's always a possibility that bugs can happen.

Upgrading from `0.1.1` to `0.2.0` does not change the command format as drastically as the previous update, so I think it should go smoothly. If you find out that some command appears to be wrong after either of the updates, feel free to comment in a new issue, and you can add examples of how a particular command was defined before an update and how it looks like after an update. And did the updates affect hotkeys if you had assigned them to your shell commands? Hotkeys should stay the same after the updates. In `0.0.0` and `0.1.0` there was a bug that hotkeys might change, at least if you deleted some shell commands. from `0.1.1` onwards, this hotkey problem should not occur.

> Since I'm on MacOS I will make the OS test and report to you too (if its okay for you :) )

Yes please, that would be nice! 🙂 Mac test comments can be added to issue #1 . If you want, you can use similar testing commands that were used by @skipadu during the first Mac test, or use your own shell commands to test it.

**Comment by FelipeRearden** [comment]
Hello again @Taitava !!!!

`False Alarm`: everything is perfect with `0.0.1` `0.1.1` and `0.2.0` : I made a mistake between `echo` and `printf` between the releases that was driving me crazy.
- Sorry for the mistake, it's hard for me to understand the bash commands - its a new world for me :)

From my test the `0.2.0` is perfect. (I will update our #1 in a few minutes with my shell commands)

I found a little little improvement that I will talk about on the next comment. 

---

I just wanna say thank for what you are doing. I will share my humble workflows with you and our friends in a few days but I just wanna take this moment to emphasize how grateful I'm with your plug-in and to you. 
- I'm being able to create workflows with Obsidian that wasn't possible before 
- Since I don't how to code, I'm very happy to use Shell Commands to make my workflows dreams come true. 

And its very nice the way you use git to share with us your vision, steps, problems and future features. 
- This make more easy to me as a user and tester to learn the best way to communicate with you. 

I can wait for the new workflows that I will be able to create!

Thank again @Taitava !!!

**Comment by FelipeRearden** [comment]
A little improvement:

If possible/feasible the window that opens to define the alias should focus in the text field. This way, I don't have to press the mouse click to start tipping 

**window today:**
![a001](https://user-images.githubusercontent.com/85180696/132993372-a769558f-28c5-46b9-86fa-ced523eb9c85.png)

**new window:**
![a002](https://user-images.githubusercontent.com/85180696/132993393-3d67d71e-e731-4f0f-bbe6-2ec9455a62c1.png)
- my print screen is not showing but the text cursor correctly in the text field.

For someone like me who uses keyboard shortcuts for everything, would be an amazing QoL.

Thanks :)

**Comment by Taitava** [comment]
Thank you again for your kind words! ❤️ I'm happy to hear that this plugin is useful! 🙂 

> False Alarm: everything is perfect with 0.0.1 0.1.1 and 0.2.0 : I made a mistake between echo and printf between the releases that was driving me crazy.
> - Sorry for the mistake, it's hard for me to understand the bash commands - its a new world for me :)

No problem! It's better to bring up possible issues, then we can discuss them together and try to find a solution. No matter if it turns out to be a *"false alarm"*, more important is to find a solution 🙂 . And generally in some cases it might be that software works actually ok, but documentation needs improvement, which can be found out by getting to know what kind of issues users run into.

> And its very nice the way you use git to share with us your vision, steps, problems and future features.

Yea, I like it too. Writing things up here in GitHub keeps me a bit more organised and eases my own work too, when I don't have to keep everything in my head. Of course I could use Obsidian for that, but I like it when programming code related stuff is right next to the code itself, and that everybody else can comment on it, even though my repositories don't typically draw much attention.

> If possible/feasible the window that opens to define the alias should focus in the text field. This way, I don't have to press the mouse click to start tipping

Great idea! I like this kind of small improvements. Making fields to have focus on default may sound like "small" issue, but these kind of "annoyances" make the user's brain to stop concentrating for a while just to find out how to get typing to that one field. That breaks the workflow of a thinking process and is not user friendly. So, improving these "small" things helps actually a lot. 👍 

I'll reopen this issue now and add a checkbox for this improvement:

- [ ] Make alias field to have focus when the modal is opened

The improvement should be easy to make, but I don't know yet when I'm going to release it, as building releases has a bit of work and I'd like to have more changes too. But it'll come out eventually! 🙂

**Comment by FelipeRearden** [comment]
@Taitava 100% agree with you . Being open is the best policy and everybody wins.
- This is one of the reasons that Obsidian Community is so strong.

I’m glad you like this “small” feature :)

No rush :) the version is strong and 100% working.  In my opinion this new feature could be stored for a new version in the feature. 

I wish you a fantastic Sunday!

**Comment by Taitava** [comment]
Thank you and have a nice day too! 🙂

The focus thing is now programmed and will be released in the next version, whenever it will come out.

**Comment by FelipeRearden** [comment]
Focus on field is perfect on MacOS - release 0.0.3 !
