### ISSUE TITLE
[Feature Request] `{{tags:separator}}` --> do not prefix tags with hashes

### ISSUE THREAD

**Issue by FelipeRearden** [Taitava/obsidian-shellcommands#62]
Hello @Taitava !

As discussed  here #51 , this FR is related to add a new feature to eliminate the `#` character of the `{{tags:separator}}` to be aligned with the YAML syntax in Obsidian.

Have a great day!!!!!!

**Comment by Taitava** [comment]
Now that I have thought about this feature a bit more, there are actually two ways to solve this:
- `{{tags:separator:no-hash}}`: The one that was discussed before. Leaving out the hash `#` would require adding this second argument `:no-hash`.
- Or: `{{tags:separator}}` could leave it out always, and no second argument would be ever used. In this case, a user can get hashes by writing for example: `#{{tags:,#}}`. So, inlude the hash `#` in the *separator* argument, as well as at the very beginning of the text so that also the first tag will have this.

The latter would be technically more simple from the program logic's point of view. Also, what made suspicious about the `:no-hash` approach, was the thing that a user would need to *write more* in the variable in order to *get less* output. It felt a bit counter-intuitive. What do you think, @FelipeRearden?

**Comment by FelipeRearden** [comment]
> Or: {{tags:separator}} could leave it out always, and no second argument would be ever used. In this case, a user can get hashes by writing for example: #{{tags:,#}}. So, inlude the hash # in the separator argument, as well as at the very beginning of the text so that also the first tag will have this.

That's the difference between a genius and a normal person. Excellent approach @Taitava !!!!!!!!!!!!!!!!
- 1000% agree with this 

In  this case, the easiest way is the right/best way :)

**Comment by Taitava** [comment]
>     * Or: `{{tags:separator}}` could leave it out always, and no second argument would be ever used. In this case, a user can get hashes by writing for example: `#{{tags:,#}}`. So, inlude the hash `#` in the _separator_ argument, as well as at the very beginning of the text so that also the first tag will have this.

Good, I will implement this. Technically speaking, this will be a *backwards incompatible change*, as it changes how the variable works and **requires a user to modify their commands** if they want to *keep* the old behavior. But as this project is still in a *non-stable* development state (version starts with `0.`), I don't feel too bad making this kind of change in `0.6.0`, rather than waiting for the next major version change (from `0.*.*` to `1.0.0`). If it would be a bigger backwards incompatibility, then I'd consider postponing it until `1.0.0`, but now there's no need for it.

Just pay attention to how your `{{tags}}` variable usages will change when upgrading to `0.6.0` (whenever that will be in the future).

**Comment by FelipeRearden** [comment]
Perfect @Taitava !!!!

> Good, I will implement this. Technically speaking, this will be a backwards incompatible change, as it changes how the variable works and requires a user to modify their commands if they want to keep the old behavior.

100% crystal clear !

> Just pay attention to how your {{tags}} variable usages will change when upgrading to 0.6.0 (whenever that will be in the future).

Thanks I will write in my workflow manual note about this change :)

**Comment by FelipeRearden** [comment]
Thank you very much @Taitava !!!!!!!!!!!!!!

**Comment by Taitava** [comment]
Released.
